#version: '3.8'
services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: ["npm", "run", "dev"]
    environment:
      # - DATABASE_URL=postgres://user:password@db:5432/weather
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB}
      # - REDIS_URL=redis://:your_secure_password@redis:6379
      # - REDIS_URL=redis://cache
      - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY}
      - USER_TOKEN_HEADER=${USER_TOKEN_HEADER}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      # - REDIS_URL=${REDIS_URL}
      - REDIS_URL=redis://${REDIS_CONTAINER_NAME}
      - PORT=${BACKEND_PORT}
    ports:
    - "${BACKEND_PORT}:${BACKEND_PORT}"
      # - "${BACKEND_PORT}:${BACKEND_PORT}"
    # networks:
    #   - backend_network
    depends_on:
      - db
      - redis
    links:
      - redis

  frontend:
    build: ./frontend
    ports:
      # - "${FRONTEND_PORT}:${FRONTEND_PORT}"
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    stdin_open: true
    depends_on:
      - backend
    environment:
      - PORT=${FRONTEND_PORT}
      - REACT_APP_USER_TOKEN_HEADER=${USER_TOKEN_HEADER}
      - REACT_APP_API_URL=http://localhost:${BACKEND_PORT}/api
    volumes:
      - ./frontend:/usr/src/app/frontend
      - /usr/src/app/frontend/node_modules
  db:
    image: postgres:13
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/01.init.sql:/docker-entrypoint-initdb.d/01.init.sql
      - ./db/02.data_seed.sql:/docker-entrypoint-initdb.d/02.data_seed.sql
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    # networks:
    #   - backend_network
  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: pgadmin4_container
  #   restart: always
  #   ports:
  #     - "8888:80"
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: user@domain-name.com
  #     PGADMIN_DEFAULT_PASSWORD: password
  #   depends_on:
  #     - db
  #   # volumes:
  #   #   - pgadmin-data:/var/lib/pgadmin

  # redis:
  #   # image: redis:alpine
  #   image: redis
  #   command: ["redis-server", "--requirepass", "your_secure_password"]
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data

  redis:
    image: redis
    container_name: ${REDIS_CONTAINER_NAME}
    expose:
      - ${REDIS_PORT}
    volumes:
      - redis_data:/data
    # networks:
    #   - backend_network

volumes:
  db_data:
  redis_data:
# networks:
  # backend_network:
  #   driver: bridge